apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: test
  labels:
    app: fullstack-microservices
data:
  url_frontend: "/backend"
  gateway_url: "http://gateway-microservice-svc:8080"
  user_service_url: "http://user-microservice-svc:8081"
  blog_service_url: "http://blog-microservice-svc:8082"
  like_service_url: "http://like-microservice-svc:8085"