apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: test
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-c
          image: datnguyen10102004/frontend:release-c94c6efc7c6c51e57997c466aca27c6b727dcdf3
          ports:
            - containerPort: 80