apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice-svc
  namespace: staging
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microservice-deployment
  namespace: staging
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-c
          image: datnguyen10102004/gateway:release_v2.0
          env:
            - name: BLOG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: blog_service_url
            - name: LIKE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: like_service_url
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: user_service_url
          ports:
            - containerPort: 8080
